/*
auto-generated by: https://github.com/react-spring/gltfjsx
author: impoimpo (https://sketchfab.com/impoimpo)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/elon-musk-running-6ad4bbc11db84e29aa270089d143b38c
title: Elon Musk Running
*/

import * as THREE from 'three'
import React, { useRef, useState, useEffect } from 'react'
import { useLoader, useFrame } from 'react-three-fiber'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useLoader(GLTFLoader, '/Elon/scene.gltf')

  const actions = useRef()
  const [mixer] = useState(() => new THREE.AnimationMixer())
  useFrame((state, delta) => mixer.update(delta))
  useEffect(() => void mixer.clipAction(animations[0], group.current).play(), [])
  return (
    <group ref={group} {...props} dispose={null}>
      
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group scale={[0.3, 0.3, 0.3]}>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <primitive object={nodes._rootJoint} />
            <group position={[0, -2.9, 158.42]} rotation={[Math.PI / 2, 0, 0]} />
            <skinnedMesh
              material={materials.bow_tie}
              geometry={nodes['bow_tie_bow tie_0'].geometry}
              skeleton={nodes['bow_tie_bow tie_0'].skeleton}
            />
            <skinnedMesh
              material={materials.Blazer}
              geometry={nodes.Blazer_Blazer_0.geometry}
              skeleton={nodes.Blazer_Blazer_0.skeleton}
            />
            <skinnedMesh
              material={materials.Henley_Longsleeve}
              geometry={nodes['Henley_Longsleeve_Henley Longsleeve_0'].geometry}
              skeleton={nodes['Henley_Longsleeve_Henley Longsleeve_0'].skeleton}
            />
            <skinnedMesh
              material={materials.Jeans}
              geometry={nodes.Jeans_Jeans_0.geometry}
              skeleton={nodes.Jeans_Jeans_0.skeleton}
            />
            <skinnedMesh
              material={materials.Boots}
              geometry={nodes.Boots_Boots_0.geometry}
              skeleton={nodes.Boots_Boots_0.skeleton}
            />
            <skinnedMesh
              material={materials.Std_Skin_Head}
              geometry={nodes.CC_Base_Body1_Std_Skin_Head_0.geometry}
              skeleton={nodes.CC_Base_Body1_Std_Skin_Head_0.skeleton}
            />
            <skinnedMesh
              material={materials.Std_Skin_Head}
              geometry={nodes.hands_Std_Skin_Head_0.geometry}
              skeleton={nodes.hands_Std_Skin_Head_0.skeleton}
            />
            <skinnedMesh
              material={materials.embed_hair_male}
              geometry={nodes.Hair_a_embed_hair_male_0.geometry}
              skeleton={nodes.Hair_a_embed_hair_male_0.skeleton}
            />
            <skinnedMesh
              material={materials.eyes}
              geometry={nodes.CC_Base_Eye_eyes_0.geometry}
              skeleton={nodes.CC_Base_Eye_eyes_0.skeleton}
            />
            <skinnedMesh
              material={materials['embed_hair_male.1']}
              geometry={nodes['Hair_embed_hair_male.1_0'].geometry}
              skeleton={nodes['Hair_embed_hair_male.1_0'].skeleton}
            />
            <skinnedMesh
              material={materials.Fingernail}
              geometry={nodes.hands_Fingernail_0.geometry}
              skeleton={nodes.hands_Fingernail_0.skeleton}
            />
          </group>
        </group>
      </group>
    </group>
  )
}
